server:
  port: 8080
  error:
    include-message: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: api-gateway
  cloud:
    discovery:
        instanceId: ${spring.application.name}
        health-check-interval: 15s
      config:
        management: 
          enabled: true
    gateway:
      routes:
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
