spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: serviceA
          uri: lb://service-A
          predicates:
            - Path=/srva/**

    consul:
      discovery:
        instanceId: ${spring.application.name}
        health-check-interval: 15s
      config:
        management:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
  error:
    include-message: always
