server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 15s
      config:
        management: 
          enabled: true
    gateway:
      routes:
        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
