spring:
  application:
    name: category-service
  datasource:
    url: jdbc:mysql://localhost:1003/categories_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 15s
        config:
          management:
            enabled: true

server:
  port: 0
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
