spring:
  application:
    name: purchase-service
  data:
    mongodb:
      uri: mongodb://localhost:1006/purchases_db?createDatabaseIfNotExist=true
      database: purchases_db
      authentication-database: admin
      username: admin
      password: admin



  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 15s
        config:
          management:
            enabled: true

server:
  port: 0
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: 576D5A7134743777217A25432646294A404E635266556A586E3272357538782F

api:
  key: g4detcAAqiar3aXV5N1eyqEi0QMbI2LZ9fsUu6OvJvZH6lrbGUZKvTVMO7NqDXY3iD72sBtaZ9XwuOFWcPr64iskp04hSXwRgzQAWRgy7MLBIXhaGdtTBF75BNKLOqPt
